#!/bin/bash

# Script para generar visualización de diagramas sin PlantUML

echo "======================================"
echo "🏗️  NEXTCLOUD INFRASTRUCTURE DIAGRAMS"
echo "======================================"
echo ""

echo "📊 INFRASTRUCTURE OVERVIEW"
echo "=========================="
echo ""
echo "┌─────────────────────────────────────────────────────────────┐"
echo "│                    HOST SYSTEM (Linux)                     │"
echo "│                                                             │"
echo "│  ┌───────────────────────────────────────────────────────┐  │"
echo "│  │            Docker Network: proxy_net_next             │  │"
echo "│  │                                                       │  │"
echo "│  │  ┌──────────┐  ┌────────────┐  ┌─────────────────┐   │  │"
echo "│  │  │ CoreDNS  │  │nginx-proxy │  │   Nextcloud     │   │  │"
echo "│  │  │ :53      │  │ :80,:443   │  │   Apache+PHP    │   │  │"
echo "│  │  │          │  │            │  │   :80           │   │  │"
echo "│  │  └──────────┘  └────────────┘  └─────────────────┘   │  │"
echo "│  │                                                       │  │"
echo "│  │  ┌──────────┐              ┌─────────────────────┐   │  │"
echo "│  │  │ MariaDB  │              │      Redis          │   │  │"
echo "│  │  │ :3306    │              │      :6379          │   │  │"
echo "│  │  │          │              │                     │   │  │"
echo "│  │  └──────────┘              └─────────────────────┘   │  │"
echo "│  └───────────────────────────────────────────────────────┘  │"
echo "│                                                             │"
echo "│  ┌───────────────────────────────────────────────────────┐  │"
echo "│  │              Volume Mounts                            │  │"
echo "│  │  ./nextcloud/     ./db/        ./redis/              │  │"
echo "│  │  ./nextcloud_data/ ./swag-config/ ./coredns/         │  │"
echo "│  └───────────────────────────────────────────────────────┘  │"
echo "└─────────────────────────────────────────────────────────────┘"
echo ""

echo "🔄 DEPLOYMENT FLOW"
echo "=================="
echo ""
echo "Administrator → start.sh → System DNS Config → Docker Network"
echo "                     ↓"
echo "              CoreDNS Started → SSL Generation → Database Setup"
echo "                     ↓"
echo "              Nextcloud App → nginx-proxy → Client Access"
echo "                     ↓"
echo "              Health Checks → Monitoring → Production Ready"
echo ""

echo "🌐 NETWORK ARCHITECTURE"
echo "======================="
echo ""
echo "Internet ← → Host:53,80,443 ← → Docker Network ← → Containers"
echo "                                       ↕"
echo "Client ← → DNS Resolution ← → CoreDNS:53"
echo "       ← → HTTPS Request ← → nginx-proxy:443 ← → Nextcloud:80"
echo "                                                      ↕"
echo "                                              MariaDB:3306"
echo "                                                      ↕"
echo "                                               Redis:6379"
echo ""

echo "🔄 SYSTEM STATES"
echo "================"
echo ""
echo "[SystemClean] → [DNSConfiguring] → [DNSActive] → [SSLGenerating]"
echo "                                                         ↓"
echo "[FullyOperational] ← [ServicesStarting] ← [SSLReady] ←──┘"
echo "        ↕                                                  "
echo "[Maintenance] ← → [ErrorState] → [Troubleshooting]"
echo "        ↓                                                  "
echo "[Stopping] → [SystemStopped]"
echo ""

echo "📋 KEY COMPONENTS"
echo "=================="
echo ""
echo "🌐 DNS Service (CoreDNS)"
echo "   • Resolves nextcloud.net → 127.0.0.1"
echo "   • Handles *.nextcloud.net wildcard"
echo "   • Forwards external queries to 1.1.1.1, 8.8.8.8"
echo "   • Port 53/UDP, 53/TCP"
echo ""
echo "🔒 SSL/TLS (nginx-proxy)"
echo "   • Self-signed wildcard certificates"
echo "   • HTTPS termination on port 443"
echo "   • HTTP redirect from port 80"
echo "   • Reverse proxy to Nextcloud"
echo ""
echo "☁️  Application (Nextcloud)"
echo "   • Apache + PHP runtime"
echo "   • Nextcloud application"
echo "   • File storage and user data"
echo "   • Admin interface"
echo ""
echo "🗄️  Database (MariaDB)"
echo "   • Nextcloud database backend"
echo "   • User data and configurations"
echo "   • Transaction isolation"
echo "   • Health monitoring"
echo ""
echo "⚡ Cache (Redis)"
echo "   • Session storage"
echo "   • Application cache"
echo "   • Performance optimization"
echo "   • Password protected"
echo ""

echo "🚀 QUICK START COMMANDS"
echo "======================="
echo ""
echo "# Complete setup:"
echo "sudo ./start.sh"
echo ""
echo "# Generate SSL certificates:"
echo "./generate-ssl-certs.sh"
echo ""
echo "# Install system certificates:"
echo "sudo ./install-ssl-cert-system.sh"
echo ""
echo "# Start services:"
echo "docker-compose up -d"
echo ""
echo "# Check status:"
echo "docker-compose ps"
echo ""
echo "# View logs:"
echo "docker-compose logs -f"
echo ""
echo "# Test DNS:"
echo "dig nextcloud.net @127.0.0.1"
echo ""
echo "# Access Nextcloud:"
echo "https://nextcloud.net"
echo ""

echo "🐛 TROUBLESHOOTING"
echo "=================="
echo ""
echo "# DNS issues:"
echo "sudo ./coredns/INSTALACION/DESACTIVAR_SYSTEM_SESOLVE.sh"
echo "docker-compose restart coredns"
echo ""
echo "# SSL issues:"
echo "./generate-ssl-certs.sh"
echo "docker-compose restart nginx-proxy"
echo ""
echo "# Service issues:"
echo "docker-compose down && docker-compose up -d"
echo ""
echo "# Port conflicts:"
echo "sudo lsof -i :53,:80,:443"
echo ""

echo "======================================"
echo "✅ Infrastructure Documentation Ready"
echo "======================================"