FROM nginx:latest

# nginx.conf se copia normalmente
COPY nginx.conf /etc/nginx/nginx.conf
# Los certificados serán montados por volumen desde el host, no sobrescribir aquí
# COPY certs/ /etc/nginx/certs/
# COPY private/ /etc/nginx/private/
COPY entrypoint.sh /docker-entrypoint.d/99-generate-cert.sh

RUN chmod +x /docker-entrypoint.d/99-generate-cert.sh