FROM nginx:latest

# nginx.conf se copia normalmente
COPY nginx.conf /etc/nginx/nginx.conf

COPY entrypoint.sh /docker-entrypoint.d/99-generate-cert.sh

RUN chmod +x /docker-entrypoint.d/99-generate-cert.sh